# Generated by Django 2.2.12 on 2020-05-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trolley.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrolleyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TrolleyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('configuration', models.TextField(blank=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('manu_workers', models.TextField(blank=True)),
                ('clean_worker', models.TextField(blank=True)),
                ('check_worker', models.TextField(blank=True)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('finished_time', models.IntegerField(blank=True, null=True)),
                ('check_description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('castor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castor_stock', to='backend.Castor')),
                ('color_drawer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DrawerColor')),
                ('color_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_drawer', to='backend.Color')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Lock')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Stock')),
                ('strip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Strip')),
                ('trolley', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trolley.TrolleyOrder')),
                ('wall_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.WallType')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrolleyOrderFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('client', models.TextField(blank=True)),
                ('owner', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=trolley.models.content_file_trolley)),
                ('trolley_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trolley.TrolleyOrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='AccesoriesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True)),
                ('direction', models.TextField(blank=True)),
                ('packaging', models.TextField(blank=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Stock')),
                ('trolley_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trolley.TrolleyOrderItem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
