# Generated by Django 2.2.12 on 2020-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
