# Generated by Django 2.2.8 on 2021-04-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210402_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproduct_item', to='backend.SubProduct'),
        ),
    ]
