# Generated by Django 2.2.8 on 2021-04-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210402_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='products',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
