# Generated by Django 2.2.8 on 2021-04-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_subcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontact',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Contact'),
        ),
    ]
