# Generated by Django 2.2.8 on 2021-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_subcontact_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontact',
            old_name='telephone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='subcontact',
            name='country',
        ),
        migrations.AddField(
            model_name='subcontact',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
