# Generated by Django 2.2.8 on 2021-04-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210405_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='parent',
        ),
    ]
