# Generated by Django 2.2.8 on 2021-04-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_contact_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, max_length=400)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
    ]
