# Generated by Django 2.2.8 on 2021-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_maillist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='contact',
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
