# Generated by Django 2.2.8 on 2021-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210412_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
