# Generated by Django 2.2.8 on 2021-05-02 22:30

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_clientchatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchatter',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientchatter',
            name='pdf',
            field=models.FileField(blank=True, upload_to=backend.models.content_file_chatter),
        ),
    ]
