# Generated by Django 2.2.8 on 2021-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210502_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchatter',
            name='pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
