# Generated by Django 2.2.8 on 2021-05-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_clientchatter_pdfname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_add', models.BooleanField(default=False)),
                ('supplier_up', models.BooleanField(default=False)),
                ('supplier_del', models.BooleanField(default=False)),
                ('supplier_p_add', models.BooleanField(default=False)),
                ('supplier_p_up', models.BooleanField(default=False)),
                ('supplier_p_del', models.BooleanField(default=False)),
                ('lead_add', models.BooleanField(default=False)),
                ('lead_up', models.BooleanField(default=False)),
                ('lead_del', models.BooleanField(default=False)),
                ('mail_add', models.BooleanField(default=False)),
                ('mail_up', models.BooleanField(default=False)),
                ('mail_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserRole'),
        ),
    ]
