# Generated by Django 2.2.8 on 2021-05-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210503_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='supplier_p_add',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='supplier_p_del',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='supplier_p_up',
        ),
    ]
